server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 7655123
    url: jdbc:postgresql://localhost:5432/test
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
